# Generated by Django 2.1.1 on 2018-10-05 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mydbase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='TextMessage',
        ),
    ]
