# Generated by Django 2.1.1 on 2018-10-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mydbase', '0002_auto_20181005_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessage',
            name='avatar',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
